### ISSUE TITLE
Замінити контейнер phpmyadmin на встановлення через composer (економія 30-50MB RAM)

### ISSUE THREAD

**Issue by konfuciusu** [hurtom/toloka#24]

**Comment by konfuciusu** [comment]
Зроблю, можливо замість phpmyadmin візьму adminer

**Comment by Sensetivity** [comment]
Можна опціонально залишити phpmyadmin?

**Comment by konfuciusu** [comment]
Це якраз перевага відкритої роробки - все це пропозиції і обговорення

**Comment by konfuciusu** [comment]
phpmyadmin додає 46 залежностей в composer, залишаю його поки що в контейнері.
