### ISSUE TITLE
Міграція прав доступу до форумів (bb_auth_access)

### ISSUE THREAD

**Issue by AIlkiv** [hurtom/toloka#29]
Раніше для просталення прав доступу для конкретної групи потрібному форуму була таблиця bb_auth_access, де для група + форум було ряд колонок з різними типам прав (читати, створювати тощо)
Зараз згідно логіки в коді вони всі колонки трансформували в одну колонку int в якій використовується біт-маска для прав.
Але з веб-адмінки для групи можна дати тільки права модератора, або їх забрати.
@konfuciusu можете, будь ласка, глянути...
1. Чи справді у новому рушій не можно кастомізувати права доступу до форуму для конкретної групи?
2. Чи зараз на толоці використовується дана фіча?

**Comment by AIlkiv** [comment]
По цій задачі, всі питання знято

**Comment by yukoff** [comment]
> По цій задачі, всі питання знято

@AIlkiv, @konfuciusu А можна стисло описати, що та як - а то питання бачу, а відповідей щось ні.

**Comment by AIlkiv** [comment]
Суть питання, була у тому, на старому рушії для кожного типу прав була окрема колонка в таблиці. В новій версії тих десять колонок перетворили в одну бітову маску ну і треба було адекватно конвертувати всі дані. А для цього треба було розібратися, як воно працює для клієнтів
