### ISSUE TITLE
Додати pretty URLs

### ISSUE THREAD

**Issue by konfuciusu** [hurtom/toloka#3]
/viewtopic.php?t=1
/t1

/viewtopic.php?t=1&start=30
/t1-30

/viewtopic.php?p=1
/p1

/profile.php?mode=viewprofile&u=2
/u1

/viewforum.php?f=1
/f1

/viewforum.php?f=1&start=30
/f1-30

**Comment by Sensetivity** [comment]
візьмусь.

**Comment by konfuciusu** [comment]
Зроблено https://github.com/hurtom/toloka/commit/1d86bc098bfb0fb7274f038627b23b1d884d0921
