### ISSUE TITLE
Міграція таблиці bb_forums

### ISSUE THREAD

**Issue by AIlkiv** [hurtom/toloka#36]
Ці колонки були додані суто на толоці: move_next, recycle_move_next, move_enable
При міграції я їх не чіпатиму.
@konfuciusu  Опиши, будь ласка, що вони роблять, щоб хтось реалізував потрібний функціонал на новому рушії

**Comment by konfuciusu** [comment]
move_next, recycle_move_next, move_enable викидаємо.
