### ISSUE TITLE
Модератори груп (bb_user_group.group_moderator)

### ISSUE THREAD

**Issue by AIlkiv** [hurtom/toloka#38]
Для групи можна призначити модератора, за це відповідає колонка group_moderator в bb_group ця колонка є у всіх трьох базах.
У базі толоки ще у таблиці bb_user_group є group_moderator (в інших базах цієї колонки нема), тобто скоріш за все це якась кастомно логіка.
@konfuciusu можете, будь ласка, перевірити чи ця колонка актуальна?

**Comment by konfuciusu** [comment]
На Толоці є можливість призначити одного адміністратора групи - це `group_moderator в bb_group` і декількох модераторів - це `group_moderator в bb_user_group`.

Я думаю, що це не критична річ.

**Comment by yukoff** [comment]
@konfuciusu Я так розумію, що це ІД користувача? Тип даних не співпадає
