### ISSUE TITLE
Час і автор кожного редагування допису (bb_posts_edit)

### ISSUE THREAD

**Issue by AIlkiv** [hurtom/toloka#40]
В torrentPier 0.35 відсутня таблиця `bb_posts_edit`, а на толоці вона є.
@konfuciusu Що це за таблиця та що з нею робимо?

**Comment by konfuciusu** [comment]
Тут зберігається час і автор кожного редагування. Це треба зберегти

**Comment by yukoff** [comment]
@konfuciusu Я все ж гадаю попередня назва задачі давала контекст, так по назві одразу не зрозумієш, про що мова

**Comment by yukoff** [comment]
@konfuciusu `bb_posts_edit` не має PK - це не є ґуд. Воно 1-1 до `bb_posts`? Тобто чи вистачить PK (`post_id`)?

**Comment by yukoff** [comment]
@konfuciusu ping 😉
> `bb_posts_edit` не має PK - це не є ґуд. Воно 1-1 до `bb_posts`? Тобто чи вистачить PK (`post_id`)?

**Comment by konfuciusu** [comment]
@yukoff PK має бути `(post_id, user_id)`

**Comment by yukoff** [comment]
@konfuciusu Дякую, підкорегував. З цим наче все. Решта в #74
