### ISSUE TITLE
Міграція bb_bt_tracker

### ISSUE THREAD

**Issue by AIlkiv** [hurtom/toloka#42]
Нові поля:
peer_hash
client
releaser
tor_type срібло/золото візьму з bb_bt_torrents.tor_type
remain
up_add
down_add
complete
Нема в новій версії:
last_stored_up
last_stored_down
stat_last_updated
expire_time

@konfuciusu  Якщо правильно зрозумів, це статистика про завантаження конкретного трекера. Дуже багато специфічних полів. Потребую допомога з розуміння звідки беруться всі ці дані (в коді не знайшов логіки заповнення) + що робимо з полями яких нема в нові версії?

**Comment by konfuciusu** [comment]
Дані в `bb_bt_tracker` - тимчасові і очищуються кожної ~години, вони не мають жодної цінності для міграції.

**Comment by yukoff** [comment]
@konfuciusu Я правильно зрозумів, що ця таблиця має бути "стокова" з upstream torrentpier?

UP: Допетрав

**Comment by yukoff** [comment]
Тут ще `topic_check_duble_tid` стовпець - мається на увазі `topic_check_double_tid`? Можу перейменувати.

**Comment by yukoff** [comment]
Для історії

### Стовпці
|   | old | new |   |
|:-:|-----|------|:-:|
| - | `torrent_id`
| | | `peer_hash` | +
| | | `topic_id` | +
| | `peer_id` | `peer_id`
| | `user_id` | `user_id`
| | `ip` | `ip`
| | `ipv6` | `ipv6`
| | `port` | `port`
| | | `client` | +
| | `uploaded` | `uploaded`
| | `downloaded` | `downloaded`
| | `complete_percent` | `complete_percent`
| | `seeder` | `seeder`
| | | `releaser` | +
| | | `tor_type` | +
| | | `remain` | +
| \* | `last_stored_up` | `up_add` | \*
| \* | `last_stored_down` | `down_add` | \*
| - | `stat_last_updated`
| | `speed_up` | `speed_up`
| | `speed_down` | `speed_down`
| | `update_time` | `update_time`
| - | `expire_time`
| | | `complete` | +

### Індекси
|   | old | new |   |
|:-:|-----|------|:-:|
| - | `UNIQUE KEY torrent_peer_id (torrent_id,peer_id)`
| | `KEY user_id (user_id)` | `KEY user_id (user_id)`
| | | `PRIMARY KEY (peer_hash)` | +
| | | `KEY topic_id (topic_id)` | +
