### ISSUE TITLE
Міграція перевірок модераторами (bb_bt_torrents.topic_check*)

### ISSUE THREAD

**Issue by AIlkiv** [hurtom/toloka#43]
Цих колонок нема у версії 0.35 і 2.2, тобто це суто кастомні. Що з ними робимо?
* `topic_check_status`
* `topic_check_uid`
* `topic_check_date`
* `topic_check_first_fid`
* `topic_check_duble_tid`
* `leechers`
* `seeders`

## Зміни назв стовпців при міграції зі старої схеми
Ці перейменування можуть потребувати змін у старому коді:

| old | new |
|-----|------|
| `topic_check_status` | `tor_status` |
| `topic_check_uid` | `checked_user_id` |
| `topic_check_date` | `checked_time` |
| `topic_check_first_fid` | `topic_check_orig_fid` |
| `topic_check_duble_tid` | `topic_check_dup_tid` |

**Comment by konfuciusu** [comment]
`topic_check` - це перевірка модератором

`topic_check_status`:
0 - не перевірено
1 - перевіряється
2 - перевірено
3 - недооформлено
4 - неправильний
5 - повтор

`topic_check_uid` - хто перевірив
`topic_check_date` - коли перевірив
`topic_check_first_fid` - оригінальний `forum_id` (якщо неправильний або повтор, реліз переноситься, це поле дозволяє його повернути)
`topic_check_duble_tid` - `topic_id` існуючого релізу (якщо ставиться повтор)

`seeders` і `leechers` можна викидати

**Comment by AIlkiv** [comment]
ок. із всіма полями зрозуміло.
На новому рушії нема логіки для topic_check_first_fid і topic_check_duble_tid. Тому пропоную залишити цей тікет саме не реалізацію їхньої логіки.

Довідка: колонка topic_check_status переїхала в tor_status

**Comment by yukoff** [comment]
### Стовпці
|   | old | new |   |
|:-:|-----|------|:-:|
| - | `torrent_id` |
| | `info_hash` | `info_hash`
| | `post_id` | `post_id`
| | `poster_id` | `poster_id`
| | `topic_id` | `topic_id`
| | | `forum_id` | +
| | `attach_id` | `attach_id`
| | `size` | `size`
| - | `piece_length` | 
| | `reg_time` | `reg_time`
| | | `call_seed_time` | +
| | `complete_count` | `complete_count`
| | `seeder_last_seen` | `seeder_last_seen`
| - | `last_seeder_uid`
| \* | `topic_check_status` | `tor_status` | \*
| \* | `topic_check_uid` | `checked_user_id` | \*
| \* | `topic_check_date` | `checked_time` | \*
| \* | `topic_check_first_fid` | `topic_check_orig_fid` | +
| \* | `topic_check_duble_tid` | `topic_check_dup_tid` | +
| - | `leechers`
| - | `seeders`
| \* | `speed_ul` | `speed_up` | \*
| \* | `speed_dl` | `speed_down` | \*

### Індекси
|   | old | new |   |
|:-:|-----|------|:-:|
| - | `PRIMARY KEY (torrent_id)` | `PRIMARY KEY (info_hash)` | +
| | `UNIQUE KEY post_id (post_id)` | `UNIQUE KEY post_id (post_id)`
| | `UNIQUE KEY topic_id (topic_id)` | `UNIQUE KEY topic_id (topic_id)`
| | `UNIQUE KEY attach_id (attach_id)` | `UNIQUE KEY attach_id (attach_id)`
| - | `UNIQUE KEY info_hash (info_hash)`
| | `KEY reg_time (reg_time)` | `KEY reg_time (reg_time)`
| | `KEY poster_id (poster_id)` | `KEY poster_id (poster_id)`
| | `KEY size (size)` | | +
| - | `KEY topic_check_uid (topic_check_uid)` | `KEY checked_user_id (checked_user_id)` | +
| | | `KEY forum_id (forum_id)` | +

### Міграція даних
```sql
UPDATE bb_bt_torrents, bb_topics
SET bb_bt_torrents.tor_type = bb_topics.topic_type_gold,
    bb_bt_torrents.forum_id = bb_topics.forum_id,
    bb_bt_torrents.call_seed_time = bb_topics.call_seed_time
WHERE bb_bt_torrents.topic_id = bb_topics.topic_id;
```

**Comment by yukoff** [comment]
@konfuciusu,
Отже викидаються (в [попередньому коментарі](#issuecomment-322373505) позначені "`-`"):
* `torrent_id`
* `piece_length`
* `last_seeder_uid`
* `leechers`
* `seeders`

Чи все вірно (плюс ще запит міграції з попереднього коментаря в частині `bb_bt_torrents.tor_type = bb_topics.topic_type_gold`)?

**Comment by konfuciusu** [comment]
@yukoff ці точно не потрібні:
```
piece_length
piece_length
last_seeder_uid
leechers
seeders
```

`torrent_id` теж не несе ніякої інформації, але якщо його викидати, треба переконатися, що немає таблиць, які би від нього залежали, як, наприклад, `bb_bt_tor_dl_stat` в старій базі.

Так, `bb_bt_torrents.tor_type = bb_topics.topic_type_gold`

**Comment by yukoff** [comment]
@konfuciusu,
Для `bb_bt_tor_dl_stat` я зробив міграцію і він (`torrent_id`) там дропається. Загалом `torrent_id` мігрується для цих:
* `bb_bt_torrents`
* `bb_bt_tor_dl_stat`
* `bb_bt_tracker`

**Comment by yukoff** [comment]
@konfuciusu, я закриваю цей, оскільки все необхідне зроблено в #74. Якщо потрібно буде щось робити по БД - тоді його просто треба перевідкрити.

Ось зміни назв полів при міграції зі старої схеми, які можливо потребуватимуть змін у старому коді:

| old | new |
|-----|------|
| `topic_check_status` | `tor_status` |
| `topic_check_uid` | `checked_user_id` |
| `topic_check_date` | `checked_time` |
| `topic_check_first_fid` | `topic_check_orig_fid` |
| `topic_check_duble_tid` | `topic_check_dup_tid` |
