### ISSUE TITLE
Міграція статистики завантажень і бонусів (bb_bt_users)

### ISSUE THREAD

**Issue by AIlkiv** [hurtom/toloka#47]
Треба зв'язати старі колонки з новими.
На толоці є колонки:
u_bonus_total
u_bonus_today
u_bonus_hourly
u_down_today
u_up_today
u_bonus_yday
u_down_yday
u_up_yday
max_up_speed
max_down_speed
ratio_nulled
u_up_old
u_down_old
u_bonus_old
max_up_speed_old
u_releases
can_leech

На новому рушії:
u_up_release
u_up_bonus
up_today
down_today
up_release_today
up_bonus_today
points_today
up_yesterday
down_yesterday
up_release_yesterday
up_bonus_yesterday
points_yesterday

При можливості варто зв'язати старі колонки з новими.
Я для тих що залишиться треба буде переносити логіку заповнення і використання із сорсів толоки.

**Comment by konfuciusu** [comment]
Викидаємо:

```
u_bonus_hourly
max_up_speed
max_down_speed
ratio_nulled
u_up_old
u_down_old
u_bonus_old
max_up_speed_old
u_releases
can_leech
```

Решта:
u_bonus_total - u_up_bonus
u_bonus_today - up_bonus_today
u_down_today - down_today
u_up_today - up_today
u_bonus_yday - up_bonus_yesterday
u_down_yday - down_yesterday
u_up_yday - up_yesterday

0- u_up_release
0 - up_release_today
0- points_today
0 - up_release_yesterday
0 - points_yesterday

**Comment by yukoff** [comment]
| old | new |
|---|---|
| `user_id` | `user_id` |
| `auth_key` | `auth_key` |
| `u_up_total` | `u_up_total` |
| `u_bonus_total` | `u_up_bonus`
| `u_down_total` | `u_down_total` |
| `u_bonus_today` | `up_bonus_today` |
| `u_bonus_hourly` | -
| `u_down_today` | `down_today` |
| `u_up_today` | `up_today` |
| `u_bonus_yday` | `up_bonus_yesterday` |
| `u_down_yday` | `down_yesterday` |
| `u_up_yday` | `up_yesterday` |
| `max_up_speed` | -
| `max_down_speed` | -
| `ratio_nulled` | -
| `u_up_old` | -
| `u_down_old` | -
| `u_bonus_old` | -
| `max_up_speed_old` | -
| `u_releases` | -
| `can_leech` | -
| 0 | `u_up_release`
| 0 | `up_release_today`
| 0 | `points_today`
| 0 | `up_release_yesterday`
| 0 | `points_yesterday`

**Comment by yukoff** [comment]
Цей також доданий до #74
