### ISSUE TITLE
Баг коли додаєш голосування

### ISSUE THREAD

**Issue by Kobzar09** [hurtom/toloka#57]
Створивши тему окремо створюється голосування, варіантів відповідей не більше 6 :(
Коли відкриваєш тему вилазить ось таке
![screenshot_3](https://user-images.githubusercontent.com/29250866/27820361-f76ac862-60a6-11e7-9037-4dc78f823347.png)

**Comment by chief-j** [comment]
У тебе проблема з правами на теки. Сервер не може створити файл/теку. "no such file or directory"
Зайди у internal_data/cache і подивися, чи є там тека filecache, а у нії bb_poll_data

**Comment by Kobzar09** [comment]
В папці internal_data є тільки сache, а далі тільки файли
Ви є на Гіттері? давайте там спишемось

**Comment by Kobzar09** [comment]
Ви є на Гіттері? давайте там спишемось

**Comment by chief-j** [comment]
Буду в ~21.30

**Comment by chief-j** [comment]
Зайди у cache, і подивися, чи є там filecache

**Comment by chief-j** [comment]
Запускаєш від root?

**Comment by Kobzar09** [comment]
так
