### ISSUE TITLE
Сховище "сирих" записів з ТБ (wiki.hurtom.com)

### ISSUE THREAD

**Issue by chief-j** [hurtom/toloka#86]
https://toloka.to/t81976-90#916014
> Прохання до розробників глянути і полагодити http://wiki.hurtom.com/ - базу "сирих" записів з ТБ, яка вже не працює кілька місяців, а Адмін щось мовчить, не реагує.

**Comment by yukoff** [comment]
А от і не зрозумів =) Праворуч стрічки коментарів є додаткові дії:
* Assignees (кому назначена задача)
* Labels (оце самі ті мітки, про які була мова)
* Projects
* Milestone

Клацаєш на **Labels** і ставиш `from forum`

**Comment by yukoff** [comment]
І яке відношення має додатковий ресурс, який з кодом torrentpier (скоріш за все) ніяк не пов'язаний?

**Comment by chief-j** [comment]
@yukoff річ втім, що я не маю дозволу ставити теги
Якщо там незначна пимилка, то краще буде, якщо адміністратор зверне на це увагу.
Має пряме відношення, але ти правий, зараз ми не цим займаємося

**Comment by yukoff** [comment]
@chief-j 
> річ втім, що я не маю дозволу ставити теги

А, точно - про це я не подумав, перепрошую, не зважай тоді на мій попередній коментар. 🙇 Хай тоді так і буде, як було - `[З форуму]`, адміни виправлять назву та поставлять мітки

**Comment by yukoff** [comment]
То що вирішили з цим? Бо якось він тихенько закрився, і все... 😉

**Comment by chief-j** [comment]
Будемо вважати, що проблема вирішена
