### ISSUE TITLE
Міграція bb_bt_torrents_del

### ISSUE THREAD

**Issue by yukoff** [hurtom/toloka#96]
Стосується #7/#46 - в старій версії таблиця `bb_bt_torrents_del` є, в новій немає

**Comment by yukoff** [comment]
Відповідно до [цього коментаря](https://github.com/hurtom/toloka/pull/74#issuecomment-319951538) можна дропати.

**Comment by yukoff** [comment]
@konfuciusu Там ще тригер в старій базі вставляв дані в цю таблицю:
```sql
DELIMITER $$
CREATE TRIGGER `bb_topics_au` AFTER UPDATE ON `bb_topics`
 FOR EACH ROW if new.topic_type_gold != old.topic_type_gold then
    insert into bb_bt_torrents_del (torrent_id,info_hash,is_del,dl_percent)
    select torrent_id,info_hash,0
    ,case new.topic_type_gold when 1 then 0 when 2 then 50 when 3 then 75 when 4 then -1 else 100 end
    from bb_bt_torrents t where t.topic_id=new.topic_id
    ON DUPLICATE KEY UPDATE dl_percent=values(dl_percent);
  end if
$$
DELIMITER ;
```

Оскільки таблицю викидаємо, я так розумію його (тригер) також? Чи якось буде переноситись логіка?

**Comment by konfuciusu** [comment]
Ця логіка (таблиця + тригер) потрібна для анонсера XBTT, який більше не підтримується апстрімом. Для спрощення, ми почнемо з використання стандартного анонсера на PHP, потім можливо перейдемо або на Ocelot, або на XBTT.

Тобто, поки що дропаємо таблицю і тригер, можливо повернемося до них пізніше.

**Comment by yukoff** [comment]
@konfuciusu Ага, зрозумів - винесу в окрему задачу

**Comment by yukoff** [comment]
Створив #109 на майбутнє, також #108 піде в #74
