### ISSUE TITLE
Міграція bb_bt_users_dl_status

### ISSUE THREAD

**Issue by yukoff** [hurtom/toloka#97]
Стосується #7/#46 - в старій версії таблиця `bb_bt_users_dl_status` є, в новій немає

**Comment by yukoff** [comment]
@konfuciusu Я так розумію, таблиця переїжджає "як є"?

**Comment by konfuciusu** [comment]
Відповідник в TP2: `bb_bt_dlstatus`
зберегти: `compl_count`
викинути: `drop_release`

**Comment by yukoff** [comment]
@konfuciusu Наразі в `bb_bt_users_dl_status.update_time` зберігається тип даних `int(11)` (ще й знаковий) - я правильно розумію, що це unixtime (себто секунди)? Відповідник в новій наче `bb_bt_dlstatus.last_modified_dlstatus`, але тут DATETIME, отже треба конвертувати.

**Comment by konfuciusu** [comment]
@yukoff все правильно

**Comment by yukoff** [comment]
Ну тоді по цьому все, додав до #74. Через необхідність конвертації треба буде робити
```sql
INSERT INTO bb_bt_dlstatus
    (user_id, topic_id, user_status, compl_count, last_modified_dlstatus)
SELECT
    user_id,
    topic_id,
    user_status,
    compl_count,
    FROM_UNIXTIME(update_time)
FROM bb_bt_users_dl_status;
```
